on:
  push:
    branches:
      - development
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          labels: |
            autorelease: pending
            No Notification
          changelog-types: |
            [
              {"type":"BREAKING CHANGE","section":"⚠️ BREAKING CHANGES"},
              {"type":"feat","section":"Features"},
              {"type":"fix","section":"Bug Fixes"},
              {"type":"docs","section":"Chores"},
              {"type":"deps","section":"Chores"},
              {"type":"chore","section":"Chores"}
            ]
